plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

android {
    compileSdk 36

    signingConfigs {
        release {
            def storePasswordValue = System.getenv("KEYSTORE_PASSWORD") ?: (project.hasProperty("KEYSTORE_PASSWORD") ? project.property("KEYSTORE_PASSWORD") : "")
            def keyPasswordValue = System.getenv("KEY_PASSWORD") ?: (project.hasProperty("KEY_PASSWORD") ? project.property("KEY_PASSWORD") : storePasswordValue)

            storeFile file("/home/nikolay/MEGAsync/Android/release.jks")
            storePassword storePasswordValue
            keyAlias "release"
            keyPassword keyPasswordValue
        }
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 3
        versionName "1.2"
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
            signingConfig signingConfigs.release
        }
    }
    namespace "org.passwdhelper.app"
    buildToolsVersion '35.0.0'
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.5.3' // Use the latest stable version
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core-ktx:1.16.0' // Or latest
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.9.0' // Or latest
    implementation 'androidx.activity:activity-compose:1.10.1' // Or latest

    // Jetpack Compose
    implementation platform('androidx.compose:compose-bom:2025.05.01') // Use the latest BOM
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-graphics'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material-icons-extended'

    // ViewModel
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.9.0'

//    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
